import streamlit as st
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder

st.title("SeatMind AI Prototype")
st.write("Predictive Seating & Positioning Intelligence")

st.caption("Prototype screening tool for seating and postural risk. This does not replace clinical assessment.")

# Load dataset
df = pd.read_csv("Prototype AI - Sheet1.csv")

# Clean column names
df.columns = df.columns.str.strip()

target_col = "predicted_seating_postural_risk_level"

# Encode dataset
encoders = {}

for column in df.columns:
    le = LabelEncoder()
    df[column] = le.fit_transform(df[column].astype(str).str.strip().str.lower())
    encoders[column] = le

# Features and target
X = df.drop(target_col, axis=1)
y = df[target_col]

# Train model
model = RandomForestClassifier(random_state=42)
model.fit(X, y)

st.subheader("Enter child seating information")

age = st.number_input("Age", min_value=0.0, max_value=100.0, value=5.0)

gender = st.selectbox("Gender", encoders["Gender"].classes_)

current_seating_setup = st.selectbox(
    "Current Seating Setup",
    encoders["current_seating_setup"].classes_
)

mobility_level = st.selectbox(
    "Mobility Level",
    encoders["mobility_level"].classes_
)

sitting_support_level = st.selectbox(
    "Sitting Support Level",
    encoders["sitting_support_level"].classes_
)

pelvic_alignment_while_sitting = st.selectbox(
    "Pelvic Alignment While Sitting",
    encoders["pelvic_alignment_while_sitting"].classes_
)

back_trunk_position_while_sitting = st.selectbox(
    "Back / Trunk Position While Sitting",
    encoders["back_trunk_position_while_sitting"].classes_
)

head_control_while_sitting = st.selectbox(
    "Head Control While Sitting",
    encoders["head_control_while_sitting"].classes_
)

body_stiffness_movement_pattern = st.selectbox(
    "Body Stiffness / Movement Pattern",
    encoders["body_stiffness_movement_pattern"].classes_
)

sits_stable_without_position_loss = st.selectbox(
    "Sits Stable Without Position Loss",
    encoders["sits_stable_without_position_loss"].classes_
)

ability_to_adjust_position_independently = st.selectbox(
    "Ability to Adjust Position Independently",
    encoders["ability_to_adjust_position_independently"].classes_
)

sitting_endurance = st.selectbox(
    "Sitting Endurance",
    encoders["sitting_endurance"].classes_
)

pain_or_discomfort_during_sitting = st.selectbox(
    "Pain or Discomfort During Sitting",
    encoders["pain_or_discomfort_during_sitting"].classes_
)

skin_redness_pressure_history = st.selectbox(
    "Skin Redness / Pressure History",
    encoders["skin_redness_pressure_history"].classes_
)

if st.button("Predict Seating Risk"):

    input_data = pd.DataFrame([{
        "age": age,
        "Gender": gender,
        "current_seating_setup": current_seating_setup,
        "mobility_level": mobility_level,
        "sitting_support_level": sitting_support_level,
        "pelvic_alignment_while_sitting": pelvic_alignment_while_sitting,
        "back_trunk_position_while_sitting": back_trunk_position_while_sitting,
        "head_control_while_sitting": head_control_while_sitting,
        "body_stiffness_movement_pattern": body_stiffness_movement_pattern,
        "sits_stable_without_position_loss": sits_stable_without_position_loss,
        "ability_to_adjust_position_independently": ability_to_adjust_position_independently,
        "sitting_endurance": sitting_endurance,
        "pain_or_discomfort_during_sitting": pain_or_discomfort_during_sitting,
        "skin_redness_pressure_history": skin_redness_pressure_history
    }])

    for column in input_data.columns:
        input_data[column] = encoders[column].transform(
            input_data[column].astype(str).str.strip().str.lower()
        )

    prediction_code = model.predict(input_data)[0]
    prediction_label = encoders[target_col].inverse_transform([prediction_code])[0]

    st.subheader("Prediction Result")

    if prediction_label.strip().lower() == "high":
        st.error("Predicted Seating & Postural Risk Level: HIGH")
        st.write("Recommended Action: A full adaptive seating and postural assessment is strongly recommended.")

    elif prediction_label.strip().lower() == "moderate":
        st.warning("Predicted Seating & Postural Risk Level: MODERATE")
        st.write("Recommended Action: Seating review and close monitoring are recommended.")

    else:
        st.success("Predicted Seating & Postural Risk Level: LOW")
        st.write("Recommended Action: Continue monitoring posture, comfort, skin, and sitting tolerance.")

    st.caption("This result is generated by an early prototype model and should be interpreted by a qualified clinician.")
